app = "test-cmr-website"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"

[[mounts]]
  source = "dashboard-json"
  destination = "/app/dashboard-app/json"

[[services]]
  internal_port = 3001
  protocol = "tcp"

  [[services.ports]]
    port = 80
